name: Crear PR desde Issue con etiqueta

on:
  issues:
    types: [opened, labeled]

jobs:
  create-pr:
    # Solo corre si la etiqueta 'auto-pr' est치 presente
    if: contains(github.event.issue.labels.*.name, 'auto-pr')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Crear PR con archivo desde issue
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: issue-${{ github.event.issue.number }}
        commit-message: "A침adir archivo desde issue #${{ github.event.issue.number }}"
        title: "PR autom치tica issue #${{ github.event.issue.number }}"
        body: "PR creada autom치ticamente a partir del issue #${{ github.event.issue.number }}"
        changes: |
          src/content/resource/archivo-issue-${{ github.event.issue.number }}.json <<EOF
          ${{ github.event.issue.body }}
          EOF
