name: Crear PR desde Issue con etiqueta

permissions:
  contents: write
  pull-requests: write

on:
  issues:
    types: [labeled]

jobs:
  create-pr:
    if: contains(github.event.issue.labels.*.name, 'auto-pr')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Crear archivo JSON desde body del issue
      run: |
        mkdir -p src/content/resource
        echo '${{ github.event.issue.body }}' > temp_body.json
        slug=$(jq -r '.slug' temp_body.json)
        echo '${{ github.event.issue.body }}' > src/content/resource/${slug}.json
        rm temp_body.json

    - name: Crear PR
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: issue-${{ github.event.issue.number }}
        commit-message: "Añadir archivo desde issue #${{ github.event.issue.number }}"
        title: "PR automática issue #${{ github.event.issue.number }}"
        body: "PR creada automáticamente a partir del issue #${{ github.event.issue.number }}"
        base: main
