name: Crear PR desde Issue con etiqueta

permissions:
  contents: write
  pull-requests: write

on:
  issues:
    types: [labeled]

jobs:
  create-pr:
    if: contains(github.event.issue.labels.*.name, 'auto-pr')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Crear archivo JSON desde body del issue
      run: |
        mkdir -p src/content/resource
        echo '${{ github.event.issue.body }}' > src/content/resource/archivo-issue-${{ github.event.issue.number }}.json

    - name: Configurar git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Crear rama nueva
      run: git checkout -b issue-${{ github.event.issue.number }}

    - name: Añadir archivo y hacer commit
      run: |
        git add src/content/resource/archivo-issue-${{ github.event.issue.number }}.json
        git commit -m "Añadir archivo desde issue #${{ github.event.issue.number }}"

    - name: Subir rama
      run: git push origin issue-${{ github.event.issue.number }}

    - name: Crear Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: issue-${{ github.event.issue.number }}
        commit-message: "Añadir archivo desde issue #${{ github.event.issue.number }}"
        title: "PR automática issue #${{ github.event.issue.number }}"
        body: "PR creada automáticamente a partir del issue #${{ github.event.issue.number }}"
        base: main
